spring:
  application:
    name: booster-cli
  main:
    banner-mode: off
  profiles:
    active: local

settings:
  vocabulary:
    pagination: 2
    practice-batch-size: 5
  notes:
    pagination: 1
